
services:
  db:
    image: postgres
    container_name: template_nest-jwt-prisma
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      - /postgres:/var/lib/postgresql/data
    mem_limit: 2g

volumes:
  db:
    name: nest-prisma-docker-db
